name: get changed Files
on: [push, pull_request]
jobs: 
    job_1:
        name: Get all Changed Files
        runs-on: ubuntu-latest
        steps:
            - id: files
              uses: jitterbit/get-changed-files@v1
            - run: |
               for changed_file in ${{ steps.files.outputs.all }}; do
                echo "Do something with this ${changed_file}."
               done
