# This is a basic workflow to help you get started with Actions

name: Daniels erster Workflow

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Here you can choose the Name of your Job (jobid)
  Daniel-baut-was:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - name: Checke Repo aus
         uses: actions/checkout@v2
       - run: |
            ls -la
            pwd
            env
        # Das wird dann ausführt.
       - run: echo Hello, world!
       - name: In Repo schreiben
         run: |
            env > umgebung.txt
            ls -la >> umgebung.txt
            ls -la $GITHUB_WORKSPACE
            ls -la
